# Generated by Django 4.1 on 2023-04-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
