# Generated by Django 4.1 on 2023-04-02 18:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_delete_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='nessuno', max_length=100)),
                ('idcard_fronte', models.ImageField(upload_to='images/idcards/fronte', verbose_name="Carta d'identita - Fronte")),
                ('idcard_retro', models.ImageField(upload_to='images/idcards/retro', verbose_name="Carta d'identita - Retro")),
                ('ts_fronte', models.ImageField(upload_to='images/TS/fronte', verbose_name='Tessera Sanitatia - Fronte')),
                ('ts_retro', models.ImageField(upload_to='images/TS/retro', verbose_name='Tessera Sanitatia - Retro')),
                ('data_emissione', models.DateField(default=datetime.datetime(2023, 4, 2, 20, 50, 3, 574209))),
                ('data_scadenza', models.DateField(default=datetime.datetime(2023, 4, 2, 20, 50, 3, 574209))),
                ('numero_documento', models.CharField(max_length=20)),
                ('comune_rilascio', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
